name: Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Optional: Test SSH connection
      - name: Test SSH Connection
        run: |
          ssh -i ~/.ssh/id_rsa \
              -o StrictHostKeyChecking=no \
              -p ${{ secrets.PORT }} \
              ${{ secrets.USERNAME }}@${{ secrets.HOST }} \
              "echo Connected successfully"

      # Deploy using appleboy action
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd /var/www/vhosts/votivereact.in/sortize.votivereact.in && ./.scripts/deploy.sh
